name = "Graphics"
uuid = "9c0812bf-1dda-4745-8bd8-51f4541a4496"
repo = "git@github.com:serenity4/Graphics"

[packages]
0b152c4a-7e29-418b-9258-223db38db9d9 = { name = "SwapStreams", path = "S/SwapStreams" }
0c8a7d74-93ea-4f23-9ed1-b26578bfdfe6 = { name = "XKeyboard", path = "X/XKeyboard" }
1147bd75-18e1-436d-adda-d58e854f897d = { name = "GeometryExperiments", path = "G/GeometryExperiments" }
1768915e-f209-48c3-8e70-04c8c5555943 = { name = "Entities", path = "E/Entities" }
1d686ed2-f4cc-40f7-813c-2f806c81b237 = { name = "Erosion", path = "E/Erosion" }
3680adac-b468-4089-a5b4-2beb8414818d = { name = "Anvil", path = "A/Anvil" }
3e47a1cc-29f2-4c46-afe0-95fe1d251308 = { name = "ProceduralNoise", path = "P/ProceduralNoise" }
6663bfc4-f836-4634-93ec-aee42a53a86a = { name = "BinaryParsingTools", path = "B/BinaryParsingTools" }
796b4d30-d51d-4664-90d1-7cd8560850fa = { name = "AbstractGUI", path = "A/AbstractGUI" }
84138a67-b342-4d33-8200-33cfcca52eb2 = { name = "SPIRV", path = "S/SPIRV" }
85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4 = { name = "Dictionaries", path = "D/Dictionaries" }
8fb73131-e68b-4921-b325-b6dc47707796 = { name = "Lava", path = "L/Lava" }
b96441d5-4525-4e55-9909-ccff87bff6f6 = { name = "GridHelpers", path = "G/GridHelpers" }
bd6f7047-4356-4127-96e0-7c076db9f2eb = { name = "ShaderLibrary", path = "S/ShaderLibrary" }
be1275fa-6550-422f-8b88-a5943ccecfb8 = { name = "GeometricAlgebra", path = "G/GeometricAlgebra" }
ddeb515c-cee5-4296-852d-ebf70c17d219 = { name = "Diatone", path = "D/Diatone" }
df8c6370-217a-4736-8ebc-77346b711d73 = { name = "CooperativeTasks", path = "C/CooperativeTasks" }
e5a4412f-5132-4ec5-841c-0d067f41fa94 = { name = "OpenType", path = "O/OpenType" }
